USE Vaccinations
GO

--Set the options to support indexed views.
SET NUMERIC_ROUNDABORT OFF;
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT,
   QUOTED_IDENTIFIER, ANSI_NULLS ON;

CREATE UNIQUE CLUSTERED INDEX TestINDX
   ON vaccinationsHappening ();
GO